### ISSUE TITLE
Switching and creating new tabs extremely slow when sidebar is enabled

### ISSUE THREAD

**Issue by suan** [hetima/SafariStand#11]
I'm on OS X Yosemite and Safari 8.0.2. When the SafariStand sidebar is enabled, and with ~ 40 tabs open, switching tabs or creating new ones have a lag of about 2 seconds. When I disable the sidebar those actions become instant again.

When I restart EasySIMBL and Safari with the sidebar the delay is not there, but after a few minutes it becomes slow again.

**Comment by Cueball** [comment]
I see this too. Haven't reported it until now since I was on 10.10.2 pre-release (with Safari 8.0.3), but now that 10.10.2 has been released, this is an issue.

Using the Console Panel tab view helps, but it too slows down over time (although not to quite the same extent, from what I can tell).

Initial thoughts? I do notice the "close tab widget" appearing and disappearing _very slowly_ whenever I run the mouse over the list of tabs in the sidebar. Perhaps only showing the "close tab widget" after tab mouseover > 0.5 seconds (or some value that's user-defined in SafariStand preferences)?

**Comment by zdlo** [comment]
Same problem here... It started soon after upgrading to 8.0.208 from 8.0.202.

I can't open even half the amount of tabs I used be able to open before, without Safari slowing down.

I guess it has something to do with the "close tab" cross trying to follow the pointer.

**Comment by zdlo** [comment]
It also causes Yosemite to freeze-crash once everyday.

**Comment by jamdox** [comment]
I also have this problem.  MBA mid 2013, current safari.

The rollover of the x from the favicon gets slower and slower, and blocks tab switching.

thanks

**Comment by hetima** [comment]
It's fixed in 8.0.209
thanks

**Comment by Cueball** [comment]
It's improved in .209, but it's not fixed :-/ Shows up in one window with as few(!) as 40 tabs open in sidebar.

**Comment by vjpr** [comment]
Awesome plugin! But very slow in `8.0.209`. Looking forward to it being fixed.

**Comment by bkonia** [comment]
Having this same problem in 8.0.210. The sidebar is completely unusable. This is with OS X 10.10.3 on a brand new Macbook Pro with the Core i7 CPU and 16 GB of RAM.

**Comment by hetima** [comment]
adjusted more. I think it's getting better in 8.0.211.
